apiVersion: apps/v1
kind: Deployment
metadata:
  name: backend-feed
spec:
  selector:
    matchLabels:
      run: backend-feed
  replicas: 1
  template:
    metadata:
      labels:
        run: backend-feed
    spec:
      containers:
      - name: backend-feed
        image: abodaa/udagram-api-feed:v1
        ports:
        - containerPort: 80
        resources:
          requests:
            memory: "4024Mi"
            cpu: "250m"
          limits:
            memory: "5024Mi"
            cpu: "500m"       
