version: 2.1

jobs:
  app:
    docker:
      - image: circleci/node:13.8.0
    steps:
      - checkout
  build-docker:
    machine: true
    steps:
      - checkout

      - run:
          name: docker login
          command: |
              echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_USERNAME" --password-stdin
      
      - run:
          name: Build Docker images
          command: |
            echo "BUILDING IMAGES..."
            docker build -t udagram-api-feed ./udagram-api-feed
            docker tag udagram-api-feed abodaa/udagram-api-feed:v1

            docker build -t udagram-api-user ./udagram-api-user
            docker tag udagram-api-user abodaa/udagram-api-user:v1

            docker build -t udagram-frontend ./udagram-frontend
            docker tag udagram-frontend abodaa/udagram-frontend:v1

            docker build -t reverseproxy ./udagram-reverseproxy
            docker tag reverseproxy abodaa/reverseproxy:v1
      
      - run:
          name: Push Docker Images
          command: |
            echo "PUSHING IMAGES..."
            docker push abodaa/udagram-api-feed:v1
            docker push abodaa/udagram-api-user:v1
            docker push abodaa/udagram-frontend:v1
            docker push abodaa/reverseproxy:v1


workflows:
  default:
    jobs:
      - app
      - build-docker:
          requires: [app]
