apiVersion: apps/v1
kind: Deployment
metadata:
  name: backend-user
spec:
  selector:
    matchLabels:
      run: backend-user
  replicas: 1
  template:
    metadata:
      labels:
        run: backend-user
    spec:
      containers:
        - name: backend-user
          image: abodaa/udagram-api-user:v1
          ports:
            - containerPort: 80
          resources:
            requests:
              memory: "4024Mi"
              cpu: "250m"
            limits:
              memory: "5024Mi"
              cpu: "500m"

             